apiVersion : apps/v1
kind : Deployment
metadata : 
  name : blog
spec :
  selector:
    matchLabels:
      app : blog-app
  replicas : 2
  template:
    metadata :
      labels:
        app: blog-app
    spec:
      containers:
        - name : blog-app
          image : bhargavram2309/blogging:latest
          imagePullPolicy: Always
          ports:
            - containerPort : 8080
      imagePullSecrets:
        - name: regcred



---

apiVersion: v1
kind: Service
metadata:
  name: bloggingapp-ssvc
spec:
  selector:
    app: blog-app
  ports:
    - protocol: "TCP"
      port: 80
      targetPort: 8080
  type: LoadBalancer
              

